name: Django Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install GDAL library
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev


      - name: Set up Django environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up GDAL environment
        run: |
          echo "export GDAL_LIBRARY_PATH=/usr/lib/libgdal.so" >> $GITHUB_ENV
      - name: Copy secrets.json
        run: 'echo "$SECRETS" > $GITHUB_WORKSPACE/config/settings/secrets.json'
        shell: bash
        env:
          SECRETS: ${{secrets.STAGING_SECRET_CONF}}
      - name: Run Django tests
        run: |
          source venv/bin/activate
          python -W ignore manage.py test
